# Generated by Django 4.2.16 on 2024-10-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='latitude',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='longitude',
            field=models.TextField(null=True),
        ),
    ]
